# Generated by Django 5.1.6 on 2025-02-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(default='xs,s,m,l,xl', max_length=50),
        ),
    ]
